name: Spring Boot CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Compile and run tests (test profile)
        env:
          SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
          SPRING_DATASOURCE_USERNAME: test_user
          SPRING_DATASOURCE_PASSWORD: testing
        run: |
          ./mvnw clean compile test -Dspring.profiles.active=test

      - name: Build Docker Image (prod profile)
        run: docker build -t myapp:latest --build-arg SPRING_PROFILES_ACTIVE=prod .

      - name: Set up environment variables for Docker Compose
        run: |
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> $GITHUB_ENV
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> $GITHUB_ENV
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> $GITHUB_ENV
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> $GITHUB_ENV

      - name: Run docker compose
        run: docker-compose up -d

      - name: Wait for application to start
        run: |
          for i in {1..30}; do
            if curl --silent --fail http://localhost:8080/actuator/health; then
              echo "Application is up!"
              exit 0
            fi
            echo "Waiting for application..."
            sleep 2
          done
          echo "Application failed to start in time"
          exit 1

      - name: Stop docker compose
        if: always()
        run: docker-compose down
